version: '3'
services:
  webapp:
    build:
      context: .
    ports:
      - '127.0.0.1:3000:3000'

  peerjs:
    build:
      context: .
    command: yarn peerjs --port 9000
    ports:
      - '127.0.0.1:9000:9000'
